name: 'jeliasson-test1'

on:
  push:
    # Only run on these branches
    branches:
      - jeliasson-test1
      - feat/initial-ci

    # Only run on changes in the following paths
    paths:
      - '.github/workflows/jeliasson-test1.yml'
      - 'api/**'
      - 'web/**'
      - 'babel.config.js'
      - 'graphql.config.js'
      - 'package.json'
      - 'redwood.toml'
      - 'yarn.lock'

env:

  # Environment variable
  NODE_ENV: 'development'
  RUNTIME_ENV: 'dev'

  # Container Registry
  CONTAINER_REGISTRY_IMAGE_PREFIX: jeliasson-test1

jobs:
  #
  # Build
  #
  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        platform: [api, web]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./docker/jeliasson-test1/${{ matrix.platform }}/Dockerfile
          build-args: |
            NODE_ENV=${{ env.NODE_ENV }}
            RUNTIME_ENV=${{ env.RUNTIME_ENV }}
          tags: |
            ghcr.io/jeliasson/${{ env.CONTAINER_REGISTRY_IMAGE_PREFIX }}-${{ matrix.platform }}-${{ env.RUNTIME_ENV }}:latest
            ghcr.io/jeliasson/${{ env.CONTAINER_REGISTRY_IMAGE_PREFIX }}-${{ matrix.platform }}-${{ env.RUNTIME_ENV }}:${{ github.sha }}
