name: 'pi0neerpat-packages'

on:
  push:
    # Only run on these branches
    branches:
      - main
      - ci/**
      - pi0neerpat-packages

    paths:
      # Implementation specific
      - '.github/workflows/pi0neerpat-packages.yml'
      - 'docker/pi0neerpat-packages/**'

      # Redwood specific
      - 'api/**'
      - 'web/**'
      - 'graphql.config.js'
      - 'package.json'
      - 'redwood.toml'
      - 'yarn.lock'

env:
  # Environment variable
  NODE_ENV: 'development'
  RUNTIME_ENV: 'dev'

  # Container Registry
  IMAGE_PREFIX: pi0neerpat-packages

jobs:
  #
  # Build
  #
  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        platform: [api, web]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Docker build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./docker/${{ env.IMAGE_PREFIX }}/${{ matrix.platform }}/Dockerfile
          build-args: |
            NODE_ENV=${{ env.NODE_ENV }}
            RUNTIME_ENV=${{ env.RUNTIME_ENV }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/docker-${{ env.IMAGE_PREFIX }}-${{ matrix.platform }}-${{ env.RUNTIME_ENV }}:latest
            ghcr.io/${{ github.repository_owner }}/docker-${{ env.IMAGE_PREFIX }}-${{ matrix.platform }}-${{ env.RUNTIME_ENV }}:${{ github.sha }}

  #
  # Analyse
  #
  analyze:
    name: Analyse
    needs: [build]
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        platform: [api, web]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Install dependencies
        run: |
          wget https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb
          sudo apt install ./dive_0.9.2_linux_amd64.deb

      - name: Run Dive
        run: |
          CI=true dive ghcr.io/${{ github.repository_owner }}/docker-${{ env.IMAGE_PREFIX }}-${{ matrix.platform }}-${{ env.RUNTIME_ENV }}:${{ github.sha }}

      - name: Image size
        run: |
          docker images | egrep '^.*SIZE|docker\-.*'
