name: 'standal-cli-both'

on:
  push:
    # Only run on these branches
    branches:
      - main
      - standal-cli-both

    paths:
      # Implementation specific
      - '.github/workflows/standal-cli-both.yml'
      - 'docker/standal-cli-both/**'

      # Redwood specific
      - 'api/**'
      - 'web/**'
      - 'graphql.config.js'
      - 'package.json'
      - 'redwood.toml'
      - 'yarn.lock'

env:
  # Environment variable
  NODE_ENV: 'development'
  RUNTIME_ENV: 'dev'

  # Container Registry
  IMAGE_PREFIX: standal-cli-both

jobs:
  #
  # Build
  #
  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        platform: [both]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: thedavidprice
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Docker build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./docker/${{ env.IMAGE_PREFIX }}/${{ matrix.platform }}/Dockerfile
          build-args: |
            NODE_ENV=${{ env.NODE_ENV }}
            RUNTIME_ENV=${{ env.RUNTIME_ENV }}
          tags: |
            ghcr.io/redwoodjs/docker-${{ env.IMAGE_PREFIX }}-${{ matrix.platform }}-${{ env.RUNTIME_ENV }}:latest
            ghcr.io/redwoodjs/docker-${{ env.IMAGE_PREFIX }}-${{ matrix.platform }}-${{ env.RUNTIME_ENV }}:${{ github.sha }}
